stages:
  - build
  - deploy

.variables_template: &variables_definition
  variables:
    PKG_CONFIG_PATH: "/opt/lv2/lib/pkgconfig:/opt/${CI_BUILD_NAME}/lib/pkgconfig:/usr/lib/${CI_BUILD_NAME}/pkgconfig"
    BUILD_OPTS: ""

.common_template: &common_definition
  <<: *variables_definition
  stage: build
  artifacts:
    name: "${CI_PROJECT_NAME}-$(cat VERSION)-${CI_BUILD_NAME}"
    paths:
      - "${CI_PROJECT_NAME}-$(cat VERSION)/${CI_BUILD_NAME}/"

.build_template: &build_definition
  <<: *common_definition
  script:
    - meson --prefix="${CI_PROJECT_DIR}/${CI_PROJECT_NAME}-$(cat VERSION)/${CI_BUILD_NAME}" -Dlv2libdir="" --cross-file "${CI_BUILD_NAME}" ${BUILD_OPTS} build
    - ninja -C build
    - ninja -C build install

.universal_linux_template_stretch: &universal_linux_definition_stretch
  image: ventosus/universal-linux-gnu:stretch
  <<: *build_definition

.universal_linux_template_buster: &universal_linux_definition_buster
  image: ventosus/universal-linux-gnu:buster
  <<: *build_definition

.universal_linux_template_bullseye: &universal_linux_definition_bullseye
  image: ventosus/universal-linux-gnu:bullseye
  <<: *build_definition

.arm_linux_template_stretch: &arm_linux_definition_stretch
  image: ventosus/arm-linux-gnueabihf:stretch
  <<: *build_definition

.arm_linux_template_buster: &arm_linux_definition_buster
  image: ventosus/arm-linux-gnueabihf:buster
  <<: *build_definition

.arm_linux_template_bullseye: &arm_linux_definition_bullseye
  image: ventosus/arm-linux-gnueabihf:bullseye
  <<: *build_definition

.universal_w64_template: &universal_w64_definition
  image: ventosus/universal-w64-mingw32
  <<: *build_definition

.universal_apple_template: &universal_apple_definition
  image: ventosus/universal-apple-darwin
  <<: *build_definition

# building in docker
x86_64-linux-gnu-stretch:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev
  <<: *universal_linux_definition_stretch

x86_64-linux-gnu-buster:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev
  <<: *universal_linux_definition_buster

x86_64-linux-gnu-bullseye:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev
  <<: *universal_linux_definition_bullseye

i686-linux-gnu-stretch:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev:i386
  <<: *universal_linux_definition_stretch

i686-linux-gnu-buster:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev:i386
  <<: *universal_linux_definition_buster

i686-linux-gnu-bullseye:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev:i386
  <<: *universal_linux_definition_bullseye

arm-linux-gnueabihf-stretch:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev:armhf
  <<: *arm_linux_definition_stretch

arm-linux-gnueabihf-buster:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev:armhf
  <<: *arm_linux_definition_buster

arm-linux-gnueabihf-bullseye:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev:armhf libjack0:armhf
  <<: *arm_linux_definition_bullseye

aarch64-linux-gnu-stretch:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev:arm64
  <<: *arm_linux_definition_stretch

aarch64-linux-gnu-buster:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev:arm64
  <<: *arm_linux_definition_buster

aarch64-linux-gnu-bullseye:
  before_script:
    - apt-get update
    - apt-get install -y libjack-dev:arm64 libjack0:arm64
  <<: *arm_linux_definition_bullseye

#x86_64-w64-mingw32:
#  <<: *universal_w64_definition
#
#i686-w64-mingw32:
#  <<: *universal_w64_definition
#
#universal-apple-darwin:
#  <<: *universal_apple_definition

pack:
  <<: *variables_definition
  stage: deploy
  script:
    - echo 'packing up...'
  artifacts:
    name: "${CI_PROJECT_NAME}-$(cat VERSION)"
    paths:
      - "${CI_PROJECT_NAME}-$(cat VERSION)/"
