sudo: required
dist: trusty
language:
 - c
os:
 - linux
compiler:
 - gcc
before_install:
 - wget http://lv2plug.in/spec/lv2-1.12.0.tar.bz2
 - tar xjf lv2-1.12.0.tar.bz2 
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:enlightenment-git/ppa
 - sudo apt-get -q update
install:
 - pushd lv2-1.12.0 && ./waf configure --no-plugins --prefix=/usr && ./waf build && sudo ./waf install && popd
 - sudo apt-get install -y gcc-5 g++-5
 - sudo apt-get install -y libjack-dev libefl-dev libsqlite3-dev cmake
before_script:
 - export CXX="g++-5" CC="gcc-5"
 - mkdir build && pushd build
 - cmake -DCMAKE_BUILD_TYPE=Release ..
 - popd
script:
 - pushd build && make && sudo make install && popd
