language: c
os: linux
compiler:
 - gcc
 - clang
before_install:
 - wget https://github.com/libuv/libuv/archive/v1.4.2.tar.gz
 - tar xzf v1.4.2.tar.gz
install:
 - pushd libuv-1.4.2 && sh autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd
before_script:
 - mkdir build && pushd build && cmake .. && popd
script:
 - pushd build && make && ./test_varchunk && popd
